import * as Lucide from "lucide-react"
import { LucideIcon } from "lucide-react"

const iconMap: Record<string, LucideIcon> = {
  Megaphone: Lucide.Megaphone,
  Facebook: Lucide.Facebook,
  Instagram: Lucide.Instagram,
  Search: Lucide.Search,
  Youtube: Lucide.Youtube,
  Palette: Lucide.Palette,
  PenTool: Lucide.PenTool,
  ImageIcon: Lucide.ImageIcon,
  Video: Lucide.Video,
  Clapperboard: Lucide.Clapperboard,
  FileText: Lucide.FileText,
  Users: Lucide.Users,
  Target: Lucide.Target,
  BarChart3: Lucide.BarChart3,
  GraduationCap: Lucide.GraduationCap,
  HeartPulse: Lucide.HeartPulse,
  ShoppingBag: Lucide.ShoppingBag,
  UtensilsCrossed: Lucide.UtensilsCrossed,
  Home: Lucide.Home,
  Rocket: Lucide.Rocket,
  UserCircle: Lucide.UserCircle,
  ShoppingCart: Lucide.ShoppingCart,
  TrendingUp: Lucide.TrendingUp,
  Camera: Lucide.Camera,
  Sparkles: Lucide.Sparkles,
  Globe: Lucide.Globe,
  Layout: Lucide.Layout,
  Code2: Lucide.Code2,
  Smartphone: Lucide.Smartphone,
  Brain: Lucide.Brain,
  Bot: Lucide.Bot,
  Cog: Lucide.Cog,
  Server: Lucide.Server,
  Database: Lucide.Database,
  Wrench: Lucide.Wrench,
  MessageSquare: Lucide.MessageSquare,
  Cloud: Lucide.Cloud,
  CheckCircle2: Lucide.CheckCircle2,
  ArrowRight: Lucide.ArrowRight,
  ArrowUpRight: Lucide.ArrowUpRight,
  ArrowDown: Lucide.ArrowDown,
  Linkedin: Lucide.Linkedin,
  Twitter: Lucide.Twitter,
  Mail: Lucide.Mail,
  Phone: Lucide.Phone,
  MapPin: Lucide.MapPin,
  Send: Lucide.Send,
  Eye: Lucide.Eye,
  EyeOff: Lucide.EyeOff,
  X: Lucide.X,
  Menu: Lucide.Menu,
  User: Lucide.User,
  LogOut: Lucide.LogOut,
  LayoutDashboard: Lucide.LayoutDashboard,
  ChevronRight: Lucide.ChevronRight,
  ChevronDown: Lucide.ChevronDown,
  Quote: Lucide.Quote,
  Star: Lucide.Star,
  HelpCircle: Lucide.HelpCircle,
  Play: Lucide.Play,
  Award: Lucide.Award,
  Zap: Lucide.Zap,
  Shield: Lucide.Shield,
  Clock: Lucide.Clock,
  HeartHandshake: Lucide.HeartHandshake,
  Save: Lucide.Save,
  RefreshCw: Lucide.RefreshCw,
  Upload: Lucide.Upload,
  Lock: Lucide.Lock,
  AlertCircle: Lucide.AlertCircle,
  CheckCircle: Lucide.CheckCircle,
  Trash2: Lucide.Trash2,
  Edit: Lucide.Edit,
  Plus: Lucide.Plus,
  GripVertical: Lucide.GripVertical,
  MoreHorizontal: Lucide.MoreHorizontal,
  Filter: Lucide.Filter,
  Download: Lucide.Download,
  Move: Lucide.Move,
  Copy: Lucide.Copy,
  Folder: Lucide.Folder,
  Image: Lucide.Image,
  File: Lucide.File,
  FileVideo: Lucide.FileVideo,
  FileJson: Lucide.FileJson,
  FileCode: Lucide.FileCode,
  Archive: Lucide.Archive,
  Settings: Lucide.Settings,
  Bell: Lucide.Bell,
  BarChart: Lucide.BarChart,
  PieChart: Lucide.PieChart,
  Activity: Lucide.Activity,
  Calendar: Lucide.Calendar,
  Tag: Lucide.Tag,
  Bookmark: Lucide.Bookmark,
  Briefcase: Lucide.Briefcase,
  Building: Lucide.Building,
  Building2: Lucide.Building2,
  Landmark: Lucide.Landmark,
  Layers: Lucide.Layers,
  Maximize: Lucide.Maximize,
  Minimize: Lucide.Minimize,
  Monitor: Lucide.Monitor,
  Moon: Lucide.Moon,
  Sun: Lucide.Sun,
  ShieldCheck: Lucide.ShieldCheck,
  Key: Lucide.Key,
  Fingerprint: Lucide.Fingerprint,
  Crown: Lucide.Crown,
  Circle: Lucide.Circle
}

export const getIcon = (name?: string): LucideIcon => {
  if (!name) return Lucide.Circle
  return iconMap[name] || Lucide.Circle
}

export const iconNames = Object.keys(iconMap).sort()
